services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    network_mode: host
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

networks:
  dokploy-network:
    driver: bridge
    name: dokploy-network